# -*- coding: utf-8 -*-
"""33b074ec-efcb-4fa7-9139-0e079c99f197

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-02-e82d432d54e9/locations/us-central1/repositories/33b074ec-efcb-4fa7-9139-0e079c99f197
"""

# Commented out IPython magic to ensure Python compatibility.
# #create dataset
# %%bigquery
# CREATE SCHEMA IF NOT EXISTS weather_data_dataset
# OPTIONS(
#  location="us");
# 
# #create Table
# CREATE OR REPLACE EXTERNAL TABLE `qwiklabs-gcp-02-e82d432d54e9.weather_data_dataset.weather_data`
# OPTIONS (
#   format = 'CSV',
#   uris = ['gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv'],
#   skip_leading_rows = 1,
#   allow_jagged_rows = false,
#   allow_quoted_newlines = false,
#   field_delimiter = ',',
#   max_bad_records = 10
# )

# Commented out IPython magic to ensure Python compatibility.
# #Create Connection in Bigqurry to Vertex AI
# %%bigquery
# CREATE OR REPLACE MODEL
#   `weather_data_dataset.gemini_model` REMOTE
# WITH CONNECTION DEFAULT OPTIONS (ENDPOINT = 'gemini-2.0-flash');
#

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery
# CREATE OR REPLACE TABLE
# `qwiklabs-gcp-02-e82d432d54e9.weather_data_dataset.weather_data_prompted` AS (
# SELECT *
# FROM
# ML.GENERATE_TEXT(
# MODEL `weather_data_dataset.gemini_model`,
# (
#    SELECT CONCAT(
#        'Provide a sarcastic narrative weather forcast for the following data: ',
#        date, city, state, temperature_f, wind_speed_mph, precipitation_in, barometric_pressure_inHg, humidity_percent, weather_condition
#    ) AS prompt
#    FROM `qwiklabs-gcp-02-e82d432d54e9.weather_data_dataset.weather_data`
# ),
# STRUCT(
#    0.2 AS temperature, TRUE AS flatten_json_output)));